# fly.toml app configuration file generated for pfswcho-zadanie1 on 2023-05-31T21:46:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pfswcho-zadanie1"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
